### ISSUE TITLE
Bug #2 从文件读取部分情况下出错

### ISSUE THREAD

**Issue by FindHao** [FindHao/CoolHosts#4]
用户反映从文件读取功能出错。无法以较简便的方式进行debug和查看日志。准备将FileCopy功能实现从`echo`改成java的文件操作。

**Comment by FindHao** [comment]
主要是文件管理器问题。如果使用非系统的文件管理器，出来的文件路径可能不是最终真正的路径。

**Comment by onekeyhosts** [comment]
2.2.0 filecopy已修正为roottool工具的copy，该问题已解决。
